name: 'Post Cypress failures to Slack'
description: 'Posts any failures in a Cypress run to Slack along with associated videos and screenshots'
inputs:
  token:
    description: 'Slack token'
    required: true
  channels:
    description: 'Slack channels'
    required: true
  workdir:
    description: 'The path of the directory where Cypress stores its screenshots. Defaults to `./cypress`. No trailing slashes, please.'
    required: false
  message-text:
    description: 'Custom Slack message text'
    required: false
outputs: {}
runs:
  using: 'node16'
  main: 'dist/index.js'
