name: 'Post Cypress failures to Slack'
description: 'Posts any failures in a Cypress run to Slack along with associated screenshots'
inputs:
  token:
    description: 'Slack token'
    required: true
  channel:
    description: 'The Slack channel to post to'
    required: true
  workdir:
    description: 'The path of the directory where Cypress stores its screenshots. Defaults to `./cypress`. No trailing slashes, please.'
    required: false
  message-text:
    description: 'Custom Slack message text'
    required: false
outputs: {}
runs:
  using: 'node20'
  main: 'dist/index.js'
branding:
  icon: 'hash'
  color: 'blue'